### ISSUE TITLE
Replace Mapbox Nomenclature with MapLibre

### ISSUE THREAD

**Issue by lseelenbinder** [maplibre/maplibre-gl-js-docs#1]
The title covers it. Rename everything! 😄

**Comment by curran** [comment]
Also update this URL and text copy.

![image](https://user-images.githubusercontent.com/68416/102368150-8b4b4480-3f88-11eb-96a3-5f5a9256c652.png)

**Comment by curran** [comment]
Also need to update Git submodule https://github.com/maplibre/maplibre-gl-js-docs/blob/publisher-production/.gitmodules

**Comment by wipfli** [comment]
Yes let's do this step by step. I close this issue for now.
