### ISSUE TITLE
Deprecate `icon-allow-overlap`

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js-docs#122]
We we should update examples.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/pull/347 deprecates `icon-` and `text-allow-overlap`. The following examples contain this keyword and we should update them:

- [ ] add-image-stretchable.html
- [ ] animate-point-along-route.html
- [ ] filter-markers-by-input.html
- [ ] filter-markers-by-input.html
- [ ] popup-on-click.html
- [ ] popup-on-click.html
- [ ] popup-on-hover.html

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo.
I'm not sure I know what you intended to cover here, but feel free to do it in the main repo.
