### ISSUE TITLE
Update remark

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js-docs#136]
To update `remark` to the latest version, we would need to use `import` instead of `require`. This seems to be some ESM vs CommonJS thing which I don't understand. How do I have to proceed to use `remark@14.0.0`?

https://github.com/remarkjs/remark/releases/tag/14.0.0

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo. I believe this is no longer an issue, but if it is please open a new issue there.
