### ISSUE TITLE
"Add a 3D model" example does not work anymore with threejs version > r117

### ISSUE THREAD

**Issue by cigone-openindoor** [maplibre/maplibre-gl-js-docs#154]
Running this example locally work pretty well until threejs version 117.
Does not work as is after.
I've personally no idea about the root cause.

https://maplibre.org/maplibre-gl-js-docs/example/add-3d-model/

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo. I believe this is no longer an issue, but if it is please open a new issue there.
