### ISSUE TITLE
Website isn't redirecting properly

### ISSUE THREAD

**Issue by oganexon** [maplibre/maplibre-gl-js-docs#160]
Hi, was looking at the docs last week and today it doesn't work anymore. (https://maplibre.org/maplibre-gl-js-docs)

Firefox: 
```
The page isn’t redirecting properly

An error occurred during a connection to maplibre.org.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

Chrome;
```
This page isn’t workingmaplibre.org redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS
```

**Comment by HarelM** [comment]
I get the same error.
Probably related to the hugo migration...?
@wipfli @maxammann can you please check?

**Comment by maxammann** [comment]
Looks like a github pages error. Should not be related to the hugo migration.

**Comment by HarelM** [comment]
@klokan can you check what could've caused this?

**Comment by wipfli** [comment]
Houps. Yes is probably due to hugo. Let me check...

**Comment by wipfli** [comment]
We saw the same thing with /community. Directions is probably also affected @smellyshovel

**Comment by wipfli** [comment]
@maxammann maybe we should not have deleted the CNAME file since we use a custom domain? See https://gohugo.io/hosting-and-deployment/hosting-on-github/#use-a-custom-domain

**Comment by wipfli** [comment]
Thanks @oganexon for reporting :)

**Comment by wipfli** [comment]
The apex domain needs the cname file. Let me recreate one. https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by wipfli** [comment]
Though the cname file is already there... https://github.com/maplibre/maplibre.github.io/blob/gh-pages/CNAME

**Comment by wipfli** [comment]
@maxammann was right. It was an issue with gh-pages. I fixed it by changing the branch from which github pages are served from gh-pages to main and back to gh-pages.

**Comment by smellyshovel** [comment]
@wipfli GL JS works fine for me, but Directions' is still broken. Or is it just me?

**Comment by maxammann** [comment]
True, I think we also need to disable and enable GH pages there.

**Comment by smellyshovel** [comment]
I'll try to do so now. Will let you know whether it helped or not.

**Comment by wipfli** [comment]
Yeah strange stuff... good that it works again.

**Comment by wipfli** [comment]
And sorry if I was not clear: I had to switch branches in the docs repo, not in the main website.
