### ISSUE TITLE
Restrict dependabot to security updates

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js-docs#202]
The docs website uses many packages and many of them lag a few major versions behind the latest available. I wonder if it makes sense to update the packages all the time or if we should rather restrict dependabot to security updates? After all, this repo is not a library, it is just a website...

What do you think @HarelM?

**Comment by HarelM** [comment]
Well... It's complicated...
I would focus on reducing the number of dependant packages as the best direction.
It's ok to limit to security updates only, but then when there's a problem when trying to update you pay the price of not updating "as you go".
All options are valid, but I would recommend trying to simplify things to reduce dependencies and complexity in general...

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo. I believe this is no longer an issue, but if it is please open a new issue there.
