### ISSUE TITLE
remark-lint-mapbox is not in this registry when run "npm ci"

### ISSUE THREAD

**Issue by nguyenthetan1995** [maplibre/maplibre-gl-js-docs#208]
Hi all! I have problem when clone this project and run command "npm ci"
Not Found - GET https://registry.npmjs.org/@mapbox/remark-lint-mapbox/-/remark-lint-mapbox-2.4.0.tgz - Not found
npm ERR! 404
npm ERR! 404  '@mapbox/remark-lint-mapbox@https://registry.npmjs.org/@mapbox/remark-lint-mapbox/-/remark-lint-mapbox-2.4.0.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by nguyenthetan1995** [comment]
thanks you @wipfli for your solution.  I really would to looking into this! Besides, I also encountered some other problems in this project such as: when run this cmd: "cd maplibre-gl-js && npm ci && npm run build-tsc". Has an error: " Missing script: "build-tsc". I'm really having a hard time launching this project. Can you help for this! thanks you so much!

**Comment by HarelM** [comment]
Yes, build-tsc is no longer relevant.
Run npm run build-prod on one of the build scripts in maplibre-gl-js project.

**Comment by wipfli** [comment]
Ou seems like the readme is outdated. It would be great if you could update it in a pull request @nguyenthetan1995

**Comment by wipfli** [comment]
I always like to look at the CI workflows in the .github/workflows folder to find out how to build a project if the documentation is outdated...

**Comment by wipfli** [comment]
Fixed in #211
