### ISSUE TITLE
`url: mapbox://` still in docs

### ISSUE THREAD

**Issue by tordans** [maplibre/maplibre-gl-js-docs#218]
Code: https://github.com/maplibre/maplibre-gl-js-docs/blob/main/docs/pages/style-spec/sources.md?plain=1#L64-L74
Docs: https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#vector

The section below still references `mapbox://` urls:

|  |
|--|
| <img width="672" alt="image" src="https://user-images.githubusercontent.com/111561/181368145-6e75dfb7-aab5-4c8c-8fc5-e06beee80c4f.png" style="border: 1px solid red;"> |

This code looks identical to the Mapbox docs. However, in the Mapbox docs the URL schema is still referenced in the in the url param section as well https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#vector-url – but not in the Maplibre Docs https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#vector-url.

IMO, ideally the docs should be updated with those information
- update the example to how one would do this in maplibre without the mapbox-URL
- hint in both sections (the code example and the url-section), that the mapbox-URL was removed in v.2.0.0. I guess the URL section would be https://github.com/maplibre/maplibre-gl-js/commit/68732f0e1a239f470e728bbf2076ed07a7a22a4c, but I am not sure.
- provide some info to users how to migrate from mapbox-URLs or how to use mapbox tiles instead, via Maplibre (which is what I was initially looking for…)
   - This part could also be extended to the console error message `Fetch API cannot load mapbox://lorem.123. URL scheme "mapbox" is not supported.` which says what not to do but does not reference anything to solve the issue.

**Comment by tordans** [comment]
> provide some info to users how to migrate from mapbox-URLs or how to use mapbox tiles instead, via Maplibre (which is what I was initially looking for…)

Just in case someone comes here googling …
https://docs.mapbox.com/help/glossary/tileset-id/#use-a-tileset-id-to-request-tilesets-directly suggest, that there should be a regular URL per tileset that I have in https://studio.mapbox.com/tilesets/. However … here is what did not work:
- Replacing the tile id `mapbox.mapbox-streets-v8/` in `https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/12/1171/1566.mvt?access_token=pk.eyJ1IjoiaGVqY28iLCJhIjoiY2piZjd2bzk2MnVsMjJybGxwOWhkbWxpNCJ9.L1UNUPutVJHWjSmqoN4h7Q`
- Also not, when I make my tileset public
- It is unclear which access_token is referenced in the docs; using the global account token did not help

Still looking …

**Comment by HarelM** [comment]
It would be great if you could open a PR to fix this.
We should show a URL to our demotiles and not `mapbox://`.

**Comment by tordans** [comment]
@HarelM as I said, I still don't understand how to get this working. Once I do, I can propose a change.

_demotiles:_ This is what I found… https://demotiles.maplibre.org/style.json or https://demotiles.maplibre.org/tiles/tiles.json and `https://demotiles.maplibre.org/tiles/{z}/{x}/{y}.pbf` – all do not look like what I would expect in this place.

**Comment by HarelM** [comment]
https://demotiles.maplibre.org/tiles/tiles.json is the tilejson file for a vercor source that can be set to the `url` propery instead of `mapbox://...`
You can also replace this with the `tiles` property and set the https://demotiles.maplibre.org/tiles/{z}/{x}/{y}.pbf
The style.json is not a tile source which is what this documentation is exampling. :-)

**Comment by joshuaVayer** [comment]
We trying to migrate from maplibre 1.15.2 to 2.+. We currently using a custom style hosted by Mapbox wich we register in maplibre as follow:
```js 
maplibregl.accessToken = <token>;
const map = new Maplibregl.Map({
	container: "maplibre-container",
	style: "mapbox://styles/<user>/<styleId>",
	//...
});
```
Like @tordans, I can't determine which Mapbox URL I should use to retrieve the style.
This is what I tried but an error of the same kind appears : 
```js 
const map = new Maplibregl.Map({
	container: "maplibre-container",
	style: "https://api.mapbox.com/styles/v1/<user>/<styleId>/?access_token=<token>,
	//...
});
```
Here is the error that I am getting: 
![image](https://user-images.githubusercontent.com/77019747/212952063-f406b24e-b56d-4de1-8612-5576db67f263.png)

**Comment by HarelM** [comment]
You can inspect the network tab in the browser to see which url the browser is using to get the style. You can also use the plugin that adds the mapbox protocol to maplibre, or you could use mapbox-gl-js, they are working hard on their product and deserve the money.

**Comment by HarelM** [comment]
@tordans I've created a PR: #375 changed some stuff, removed others, feel free to review it.
I mainly removed references to `mapbox://` stuff in the docs and stuff related to mapbox token.
