### ISSUE TITLE
Add separate build workflow to validate latest version of maplibre-gl-js

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js-docs#237]
The `npm run test` included the `latest-version` check which was problematic. It's not disabled, but splitting it out into a separate workflow would allow us to still run all other tests but that on versions that aren't the `latest`. This is valuable to test the doc generation of unreleased versions of the upstream code.

**Comment by birkskyum** [comment]
Related to #234  #232

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo. I believe this is no longer an issue, but if it is please open a new issue there.
