### ISSUE TITLE
bottom control and Safari/iOS

### ISSUE THREAD

**Issue by cigone-openindoor** [maplibre/maplibre-gl-js-docs#255]
**maplibre-gl-js version**: 2.1.9 (and any previous version)

**browser**: Chrome/Safari on iOS

The bottom navigation bar in Chrome/iOS cover bottom controls so they are unreachable, as shown in the above screenshot.

![signal-2022-05-28-060038](https://user-images.githubusercontent.com/69067574/170809153-1cd4f3a9-a7ed-4bcd-951a-4b49e1996575.png)

The bottom navigation bar in Safari/iOS cover bottom controls so they are unreachable, as shown in the above screenshot.

![signal-2022-05-28-060943](https://user-images.githubusercontent.com/69067574/170809290-160b50f1-f36e-49f9-a32f-64736437d127.jpeg)

Expected behaviour (it works well on Chrome/MacOS):

![Capture d’écran 2022-05-28 à 06 12 34](https://user-images.githubusercontent.com/69067574/170809366-c65f8155-f43d-4fa4-88b4-3b6cbaeec608.png)

It would be nice to suggest a solution working also for Chrome/Safari on iOS

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo. I believe this is no longer an issue, but if it is please open a new issue there.
