### ISSUE TITLE
Broken GitHub links in API reference

### ISSUE THREAD

**Issue by danielfaust** [maplibre/maplibre-gl-js-docs#268]
As an example, page https://maplibre.org/maplibre-gl-js-docs/api/geography/#mercatorcoordinate contains a reference to [node_modules/maplibre-gl/src/geo/mercator_coordinate.ts](https://github.com/maplibre/maplibre-gl-js-docs/blob/dd6c5b7a81c4bd5417f94ca2a37869041660641e/node_modules/maplibre-gl/src/geo/mercator_coordinate.ts#L77-L146) directly under the heading, next to a GitHub logo, yet that linked page returns a 404.

Instead of

https://github.com/maplibre/maplibre-gl-js-docs/blob/dd6c5b7a81c4bd5417f94ca2a37869041660641e/node_modules/maplibre-gl/src/geo/mercator_coordinate.ts#L77-L146

the correct link target should be

https://github.com/maplibre/maplibre-gl-js/blob/224a8c86c8bb3b9abe2a95193b840e710eeba3b6/src/geo/mercator_coordinate.ts#L77-L146

It appears that this is happening with every reference to GitHub.

**Comment by HarelM** [comment]
Might be relevant to the removal of the submodule lately.
@birkskyum @wipfli can you guys share your thoughts?

**Comment by birkskyum** [comment]
I definitely is. Before when the submodule were in the root and had the same folder name as the repo 'maplibre-gl-js' it would point to the right URL.
