### ISSUE TITLE
Building maplibregljs-starter

### ISSUE THREAD

**Issue by dayjournal** [maplibre/maplibre-gl-js-docs#293]
I have built a build environment that allows me to easily start "MapLibre GL JS" with a combination of "MapLibre GL JS," "Vite," and "TypeScript."
Do you think I should import this starter into this repository as a Quickstart for builds?

https://github.com/dayjournal/maplibregljs-starter

**Comment by HarelM** [comment]
There are many ways to build web apps, vite is just one of them.
It can be under maplibre organization if you would like to maintain it, there's a checklist to follow in order to propose a repo to be imported into maplibre org.
There's also awesome-maplibre where you can add a link to this starter repo.
I don't think it should be part of this repo though.

**Comment by dayjournal** [comment]
Thank you for your reply. It seems my sample is not needed. Thank you.

**Comment by wipfli** [comment]
Hi @dayjournal, thanks for sharing the vite example. I think it would be nice to have some examples of how to integrate MapLibre GL JS in common frameworks.

**Comment by wipfli** [comment]
This docs repo is probably not the best place, but maybe we could have a repo like https://girhub.com/maplibre/maplibre-gl-integration-examples or framework-examples?

**Comment by wipfli** [comment]
There was once a discussion on HN that it would be nice to have some good MapLibre GL starter examples. Maybe it was here? https://news.ycombinator.com/item?id=31536217

**Comment by wipfli** [comment]
One point was I think that it is a bit hard to get the full page css stuff right such that the map fills the browser on desktop, mobile, iOS, Android... Wasn't that a concern, @ellenhp?

**Comment by ellenhp** [comment]
What I found harder than filling the full screen is filling most of the screen but allowing another element to take up the e.g. 100px that it needed. Filling the whole screen is nice but often an application may want to place a card below or above the map without covering the attribution. I needed to use JS for this, which isn't the end of the world but a well-documented way to do it with pure CSS would be amazing.

**Comment by HarelM** [comment]
The map is simply a canvas, this is regular CSS which everyone is dreaded of... :-)

**Comment by ellenhp** [comment]
I understand that, I'm just sharing what I found difficult as someone with comparatively little experience in web development because I was @ tagged in a question. :)

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo. I believe this is no longer an issue, but if it is please open a new issue there.
