### ISSUE TITLE
[Demo] Create an example to publish geo datasets on static hosts

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-js-docs#373]
## Motivation

Various government agencies and organizations often need to publish geodata. Usually organizations need to use paid services to publish them, even though the datasets might be relatively small, or the number of downloads relatively low.  I would like to propose a simple demo that would take all input geojson files and "compile" them into an easy to publish package that can be copy/pasted to a static hosting (like github pages) without any server component.  The output will have:
* a single [pmtiles](https://github.com/protomaps/PMTiles) file with all the source geojson files
* a simple maplibre-gl-js wrapper that shows that pmtile content to the users, loading data directly from the pmtiles (single static file via range requests), rather than using any kind of service
* offer download links for the whole dataset (all geojson files zipped together)
* offer a link to load each individual geojson file (each feature in pmtiles will have a tag that indicates what was the source geojson file for that feature)

## Design Alternatives

Publish data to a paid service

#### Packaging utility
A single packaging utility to
* convert geojson into pmtiles, where each geojson is a separate feature with a link to the original geojson
* copy all map-showing assets that know which pmtiles to use
* some parameter to (optionally) use some base map, either from a tile service or some simple shapes like natural earth
#### MapLibre gl-js web site assets
All the assets needed to show the needed data to a user in a browser, automatically loading optional base map and the data overlay, plus allow feature clicking to show some statistics (shape size and bbox, etc), and a download link

### Mock-Up

```
./publish --base https://example.org --geojson ./ --output ./build
```

### Concepts

publish as part of the maplibre examples, showing the usage of pmtiles, on-click file downloads, ...

### Implementation

i think the utility is better be done in Rust for speed and ease-of-deployment, while the web assets would be using maplibre-gl-js, possibly from some CDN

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo.
@nyurik @bdon do you have a small PMtiles that you can add to the demotile repo on in another place that can be used to illustrate this functionality.
I have rewritten the docs now in the main repo and it's super simple to add new examples there.
Closing, as we are archiving this repo.
Feel free to open this issue in the main repo again if this is something you would like to have.
I think a PR would be a lot simpler though :-)
