### ISSUE TITLE
Disappointing discrepancy between example thumbnail and implementation

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js-docs#378]
The thumbnail for the simple map in the [examples page](https://maplibre.org/maplibre-gl-js-docs/example/) looks very nice
![image](https://user-images.githubusercontent.com/1304610/214009796-e9f576e8-848a-46ad-b2d9-7eabef6f1889.png)

However, the view of the same area in the example itself is disappointingly different
<img width="500px" src="https://user-images.githubusercontent.com/1304610/214010899-23d75e6d-8dd0-4b3d-a182-12d55f3907fd.png"/>

Please align the example map with the thumbnail, rather than vice-versa.

**Comment by wipfli** [comment]
I think it is good to use https://demotiles.maplibre.org/style.json for the simple map because it is vendor-neutral, but maybe we should use something like zoom z2 instead of a deep zoom...
