### ISSUE TITLE
Can't update style-spec because missing rollup folder

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js-docs#389]
Since the rollup folder was remove in https://github.com/maplibre/maplibre-gl-js/pull/1986, we created a lot of broken references in the docs and lost the ability to update the style spec.

**Comment by HarelM** [comment]
So, we're even in a worse spot than I thought... :-/

**Comment by HarelM** [comment]
Link to bounty:
https://github.com/maplibre/maplibre/issues/191

**Comment by birkskyum** [comment]
Invoice https://opencollective.com/maplibre/expenses/132830
