### ISSUE TITLE
Something went wrong on the page with layers spec

### ISSUE THREAD

**Issue by spiner2000** [maplibre/maplibre-gl-js-docs#396]
https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/
![Screenshot 2023-02-16 131200](https://user-images.githubusercontent.com/1374700/219349720-39fba869-7434-42fa-bf9e-872b89ed1a00.png)

**Comment by HarelM** [comment]
Is this related to #394 maybe?

**Comment by tengl** [comment]
Tagging @SnailBones as that was the most recent commit.

**Comment by wipfli** [comment]
We removed some images which were not used by examples anymore. Maybe we removed one too many..

**Comment by SnailBones** [comment]
> We removed some images which were not used by examples anymore. Maybe we removed one too many..

That's correct, along with unused examples I removed several images used by the layers style spec. :grimacing:

My apologies! Fix here: https://github.com/maplibre/maplibre-gl-js-docs/pull/399
