### ISSUE TITLE
Create separate style-spec docs

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js-docs#400]
Similar to the libraries themselves (https://github.com/maplibre/maplibre-gl-js/issues/2149), the style-spec docs should also be split from the MapLibre GL JS docs. This is because the style-spec will have a different release cycle from maplibre-gl-js, and because the docs for these two packages are generated very differently:

* MapLibre GL JS is generated by parsing JSDoc comments
* Style Spec is a JSON document, so the docs are made in a very custom fashion.

**Comment by HarelM** [comment]
Link to bounty:
https://github.com/maplibre/maplibre/issues/191

**Comment by krishnaglodha** [comment]
As per call with @birkskyum , I'll be using https://squidfunk.github.io/mkdocs-material/ for Style Spec Documentation

**Comment by HarelM** [comment]
Great!
Make sure you check my last two comments in the following thread:
https://github.com/maplibre/maplibre-gl-style-spec/pull/23#issuecomment-1445280455
Or you could write them here, whichever works for you.

**Comment by krishnaglodha** [comment]
HI @HarelM I checked the comments. Jekyll, Hugo , Astro all are good examples based on JS, I thought to using MkDocs, as it has tons of features and very light weight. Written in Python. Final site will look something like this https://fastapi.tiangolo.com/ . Can you please give me clarity on what product should I pick ? Then I'll start creating doc. 

Thanks

**Comment by HarelM** [comment]
I don't have a preference, mkdocs is probably good too.
The product is the style-spec docs we would like to migrate.
The two sides TOC is an interesting feature I think it's good and can initiate how mature on one hand and complicated on the other hand a documentation framework can be.
Is it clear? Do you need more guidance?

**Comment by krishnaglodha** [comment]
Got it :) 

Will keep application as 3 parts. 
Left sidebar - Listing out Main Categories
Central Part - Content
Right sidebar - Section inside content

**Comment by HarelM** [comment]
Yup, also note that TOC probably is not needed on mobile, and that it should be responsive...

**Comment by krishnaglodha** [comment]
Yup. Mobile focuses on central part by default
<img width="370" alt="Screenshot 2023-03-01 at 10 27 30 PM" src="https://user-images.githubusercontent.com/47075664/222208882-52d01c44-0f11-43e0-8a17-2ec2262cbe4e.png">
and hanburger menu allows to select left sidebar
<img width="334" alt="Screenshot 2023-03-01 at 10 28 09 PM" src="https://user-images.githubusercontent.com/47075664/222209024-8deea781-5594-440c-acb2-977ebf96eb79.png">

**Comment by birkskyum** [comment]
@krishnaglodha , there is also an astro branch here (so typescript) that has most of the site working - it only lack some json data-loading from completing this bounty. it might be easier for us to maintain typescript

<img width="1541" alt="Screenshot 2023-03-01 at 18 08 42" src="https://user-images.githubusercontent.com/74932975/222211615-fd73a17f-77c7-4204-bb74-4386af17048d.png">

**Comment by birkskyum** [comment]
You can try to fire an "npm run dev" inside the docs repo here
https://github.com/maplibre/maplibre-gl-style-spec/tree/build-docs-with-astro

**Comment by birkskyum** [comment]
In hindsight an M allocated wasn't quite the right estimate, as it was merely intended to cover a clone of batfish site 😅 glad to have the ticket closed though.

**Comment by HarelM** [comment]
Well 😀 one could argue that doing a design first, rough estimation and only then proceed to implementation could have avoided this inconsistency... I'm glad this is solved as well.

**Comment by birkskyum** [comment]
This is the criteria we agreed Feb 8th that I signed up for, and I clearly had to do a ton more than that, so that's why I ask if we can elevate the bounty.

Phase 4: Create style-spec docs ([#389](https://github.com/maplibre/maplibre-gl-js-docs/issues/389), end of [#2149](https://github.com/maplibre/maplibre-gl-js/issues/2149))
- **Make a clone of maplibre-gl-js-docs where everything but the style-spec code is removed**.
- Use the files from the style-spec repo directly rather than a submodule or an npm package. It might be necessary to expose tsc compiled .js files, since batfish isn’t ts compatible.
- Deploy main branch with github pages to [maplibre.org/maplibre-gl-style-spec](http://maplibre.org/maplibre-gl-style-spec)
- Setup github action on PRs to test that docs can build
- Setup cloudflare redirect from old to new style-spec docs

**Comment by birkskyum** [comment]
OC https://opencollective.com/maplibre/expenses/135082

**Comment by wipfli** [comment]
@birkskyum delivered the work of the original scope in pull request [#23](https://github.com/maplibre/maplibre-style-spec/pull/23). However, in the review of this pull request, the maintainer expanded the scope of work which resulted in pull request [#88](https://github.com/maplibre/maplibre-style-spec/pull/88). Since the new scope was larger and included rewriting a new docs generation website, we added retroactively a bounty size XL to this ticket. This shall be a one-time exception and we require maintainers to not increase the scope of a bounty and developers to clarify design decisions before starting working on implementations.
