### ISSUE TITLE
Does maplibre terrain support terrarium format tiles?

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js-docs#406]
The documentation is self-contradictory on whether "terrarium" format is supported for terrain tiles:
https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#raster-dem

> A raster DEM source. Only supports [Mapbox Terrain RGB](https://blog.mapbox.com/global-elevation-data-6689f1d0ba65):

> ## [encoding](https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#raster-dem-encoding)
Optional [enum](https://maplibre.org/maplibre-gl-js-docs/style-spec/types/#enum). One of "terrarium", "mapbox". Defaults to "mapbox".

Is this supported or not?

**Comment by HarelM** [comment]
Fixed by #405
