### ISSUE TITLE
Broken link on `/maplibre-gl-js-docs/style-spec/` / Looking for style spec changelog

### ISSUE THREAD

**Issue by tordans** [maplibre/maplibre-gl-js-docs#417]
https://maplibre.org/maplibre-gl-js-docs/style-spec/ links to 

```html
<p>
<span class="inline-block mr6">Current version: <code>v18.0.1</code> </span>
<a class="unprose link txt-underline" href="https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/CHANGELOG.md">View changelog</a>
</p>
```

… but https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/CHANGELOG.md does not hold a changelog.

Is there a changelog for the style-spec? (That would be super helpful!)

---

Update: The link below https://github.com/maplibre/maplibre-gl-js/tree/main/src/style-spec "[Contribute on GitHub](https://github.com/maplibre/maplibre-gl-js/tree/main/src/style-spec)" is also broken.

**Comment by HarelM** [comment]
Thanks for the update, yes, there is a changelog, we've just recently moved the style-spec docs to a new repo, so there might be issues we still need to fix.
Feel free to submit a PR to fix this.
cc @birkskyum

**Comment by birkskyum** [comment]
this is the correct link
https://github.com/maplibre/maplibre-gl-style-spec/blob/main/CHANGELOG.md

**Comment by birkskyum** [comment]
Fixed by https://maplibre.org/maplibre-style
