### ISSUE TITLE
Broken expression arguments and return values

### ISSUE THREAD

**Issue by clementgayvallet** [maplibre/maplibre-gl-js-docs#421]
Most of the expression arguments and return values are displayed as `[object Undefined]`.

Here an example for the [get](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#get) expression.

---

![image](https://user-images.githubusercontent.com/11444022/222178607-3111706e-7900-4b48-b63e-02414306c35c.png)

**Comment by HarelM** [comment]
Oh, this is bad...
Thanks for taking the time to report this issue!
If you feel like pushing this fix forward feel free to submit a PR.
We are in the middle of making massive changes to the style-spec repo and docs, so this is probably an unfortunate accident.
Never-the-less, this is a bug...

**Comment by HarelM** [comment]
@birkskyum @krishnaglodha where are we with this issue?

**Comment by birkskyum** [comment]
@krisnaglodha, are you still looking into https://github.com/maplibre/maplibre-gl-js-docs/issues/400, and can you give an eta  ?

**Comment by birkskyum** [comment]
Closed by [#](https://github.com/maplibre/maplibre-style/pull/88)

See https://maplibre.org/maplibre-style/
