### ISSUE TITLE
color-switcher example does not change building colors

### ISSUE THREAD

**Issue by SnailBones** [maplibre/maplibre-gl-js-docs#423]
The ["Change a layer's color with buttons" example](https://maplibre.org/maplibre-gl-js-docs/example/color-switcher/) changes water color, but not building color. This is probably because the style used no longer contains a layer named "building," and may be fixed by updating the layer name.

**Comment by HarelM** [comment]
Can this be fixed as part of #422? Doesn't feel like this deserves an extra bounty, but let me know.
