### ISSUE TITLE
Forbidden requests

### ISSUE THREAD

**Issue by clementgayvallet** [maplibre/maplibre-gl-js-docs#439]
Examples using a MapTiler style get forbidden requests. 

Here the [add-a-marker](https://maplibre.org/maplibre-gl-js-docs/example/add-a-marker/) example.

![image](https://user-images.githubusercontent.com/11444022/226923928-5801e6af-05b8-4c2e-a17b-141017b45c54.png)

**Comment by dominiklippl** [comment]
@HarelM I have the same issue. It looks like the maptiler api token is wrong or formatted incorrectly.

![image](https://user-images.githubusercontent.com/36797134/226950240-2a0bbda2-960f-466c-b11c-e58e6e0eb949.png)

**Comment by HarelM** [comment]
@klokan can you have a look? are we reaching some limit here?

**Comment by klokan** [comment]
I am checking it...

**Comment by klokan** [comment]
Should be fixed by now.

Naked domain limit misconfigured on this key during migration to a different account. Sorry for the troubles.

Please report if any issues are remaining and we reopen.
