### ISSUE TITLE
Update link in repo description

### ISSUE THREAD

**Issue by Malvoz** [maplibre/maplibre-gl-js-docs#45]
This repo's description is still linking to https://docs.mapbox.com/mapbox-gl-js/overview/, it should be https://maplibre.org/maplibre-gl-js-docs/. 👍🏼

**Comment by wipfli** [comment]
Thanks for pointing this out. @nyurik can you update this with your admin super-powers?

**Comment by nyurik** [comment]
thanks for the heads up, fixed
