### ISSUE TITLE
Regenerate docs to remove `supported`

### ISSUE THREAD

**Issue by ibesora** [maplibre/maplibre-gl-js-docs#459]
`supported` was removed in Maplibre 3.0 but the [documentation](https://maplibre.org/maplibre-gl-js-docs/api/properties/#supported) for it was still in the code. 
I removed that in https://github.com/maplibre/maplibre-gl-js/pull/2591 but we need to update the docs to account for that change.

**Comment by HarelM** [comment]
Thanks for taking the time to open this issue.
I assume that we will regenerate the docs when we release the next version, which shouldn't take so long...
Cc @birkskyum
