### ISSUE TITLE
Update all examples to ES6

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js-docs#463]
All the examples are ES5, with `var` instead of `let` and `const` etc.

This is related to the .html files inside docs/pages/example 

It would be great to have it updated. Also, if it could be notes which examples that currently doesn't work in jsfiddle / codepen it would be good to have an overview of.

**Comment by ujwalkumar1995** [comment]
Hey @birkskyum 
I would like to work on this but I did not quite understand what do you mean by:

> Also, if it could be notes which examples that currently doesn't work in jsfiddle / codepen it would be good to have an overview of.

**Comment by birkskyum** [comment]
Cool! What I meant is that if you go to an example like this:

https://maplibre.org/maplibre-gl-js-docs/example/add-image-generated/

If you try to open it using the jsfiddle button, it can't run, presumably because the style rely on a paid tile service, and in many of the examples we probably would be fine using the free demotiles/carto styles - and it would be good to have an overview of which work.

@klokan , fyi - many examples use maptiler as the basemap, with the generous "key=get_your_own_OpIi9ZULNHzrESv6T2vL". I presume it's locked to maplibre.org, which makes it look great there, but we unfortunately have to make a change here since it crashes when the example are opened in jsfiddle/codepen etc. which we have shortcuts for. Let us know if there is some open demo-map from maptiler as well that I don't know about.

**Comment by birkskyum** [comment]
<img width="356" alt="Screenshot 2023-05-27 at 17 24 57" src="https://github.com/maplibre/maplibre-gl-js-docs/assets/74932975/590fa8d5-56f0-4fd6-8c84-b1c5aeb96410">

**Comment by klokan** [comment]
Fixed.  jsfiddle.net as well as codepen.io were already allowed...
but Origin on the requests does not come from these domains.
It comes instead from fiddle.jshell.net (?) and some codepen.io subdomains.

Happy to provide this key for maplibre examples and demos - but we need to know for what domains exactly.

**Comment by klokan** [comment]
If there is still a problem - please help me to debug the exact Origin which needs to be permitted.

**Comment by birkskyum** [comment]
Great, thanks! :)

**Comment by birkskyum** [comment]
@ujwalkumar1995 , the es6 modernization on it's own is also great, if the other task is confusing (should actually have been a separate ticket to look into that.)

**Comment by birkskyum** [comment]
@klokan , the JSFiddle seems to work now, and regarding CodePen, I believe they have the map running in an iframe with origin **https://cdpn.io** that make the requests.

**Comment by klokan** [comment]
Added @birkskyum. Thanks for info

**Comment by klokan** [comment]
@birkskyum - do we want to have stackblitz as well? What is the domain there? It looks to me they use *.webcontainer.io - correct?

**Comment by birkskyum** [comment]
@klokan , that would be great! Sounds about right - if it makes a difference, it's often from the local-credentialless.webcontainer.io subdomain.

**Comment by HarelM** [comment]
I think I updated the examples to use let instead of var.
New docs are now part of the maplibre-gl-js repo. I believe this is no longer an issue, but if it is please open a new issue there. If there's still work to update to es6 a bounty can be assigned if anyone is interested.
