### ISSUE TITLE
Add `TerrainControl` documentation

### ISSUE THREAD

**Issue by bogind** [maplibre/maplibre-gl-js-docs#468]
I'm not sure if the process is supposed to be automatic or not when the jsdoc strings for a new class are added but for some reason is seems that the [`TerrainControl`](https://github.com/maplibre/maplibre-gl-js/blob/v3.0.1/src/ui/control/terrain_control.ts) documentation wasn't generated when it was added.

I don't know if it is related to #155 but currently the only way to find the control is by seeing the [3D Terrain](https://maplibre.org/maplibre-gl-js-docs/example/3d-terrain/) example.

The JSDoc for the class seems valid and should explain the use of the control effectively.

**Comment by HarelM** [comment]
There's probably a need to manually add it, the docs aren't great in terms of generating the right stuff.
Feel free to submit a PR.

**Comment by bogind** [comment]
Opened the issue because I couldn't ind where.
If you could point me in the direction of the repo and files I need to edit I'd be glad to add it.

I could not find where the properties for the [markers and controls](https://github.com/maplibre/maplibre-gl-js-docs/blob/main/docs/pages/api/markers.js) page (which I assumed was the source for the page)
