### ISSUE TITLE
Documentation error for map.getCenter

### ISSUE THREAD

**Issue by curran** [maplibre/maplibre-gl-js-docs#52]
In https://maplibre.org/maplibre-gl-js-docs/api/map/#map#getcenter, the sample code reads:

```js
var {longitude, latitude} = map.getCenter();
```

However, this code does not work (for MapLibre version 1.14.0). The following does work:

```js
const { lng, lat } = map.getCenter(); 
```

I propose to update the sample code to the version that works.

Thanks!

**Comment by wipfli** [comment]
Hi @curran Thanks for pointing this out. Actually you were in the right repo when posting to maplibre-gl-js :) The source code for this example is here: 

https://github.com/maplibre/maplibre-gl-js/blob/b7d376a6ae7e97e0ca2a3c8d4627b87b35b5fb62/src/ui/camera.js#L153-L156

**Comment by curran** [comment]
Aha! Thank you.
