### ISSUE TITLE
.eslintrc not found by `npm lint`

### ISSUE THREAD

**Issue by marcelnormann** [maplibre/maplibre-gl-js-docs#71]
.eslintrc is not found by `npm lint`, because it searches for .eslintrc.* by default. I fixed it in 5fccff9 by adding it as a parameter to the eslint command. Maybe it woruld be more appropriate to rename the .eslintrc to .eslintrc.json so it will be found by default.

**Comment by wipfli** [comment]
I am happy with both solutions.

**Comment by marcelnormann** [comment]
I was wrong. Seems to be an older version of eslint. Solved the problem by palcing the overrides within the example sub directory: efddab4
