### ISSUE TITLE
Remove Mapbox specific code

### ISSUE THREAD

**Issue by marcelnormann** [maplibre/maplibre-gl-js-docs#74]
There is a lot of Mapbox specific code left like
- Tilestream URL
- Mapbox URLs
- Mapbox user menu
- sniffing code like Raven & Sentry
This needs to be removed

**Comment by wipfli** [comment]
@danswick I link your work here such that we don't duplicate your efforts: 

https://github.com/danswick/maplibre-gl-js-docs/commits/rm-mapbox-services

**Comment by wipfli** [comment]
https://github.com/danswick/maplibre-gl-js-docs/pull/2

**Comment by marcelnormann** [comment]
@danswick Sorry, I was not aware that you are working on the same issue. I think my current PR is "stop the bleeding" whilst yours is "close the wound".

**Comment by danswick** [comment]
No worries, @marcelnormann! My fork is a bit overkill and I was planning on simplifying anyway 😄. Instead I can just target your branch and fill in any gaps if they exist.

**Comment by marcelnormann** [comment]
> Instead I can just target your branch and fill in any gaps if they exist.

Should I set the PR back to draft mode and wait for your changes?
