### ISSUE TITLE
More elaborate example for local read/write von GeoJSON

### ISSUE THREAD

**Issue by marcelnormann** [maplibre/maplibre-gl-js-docs#77]
The current example for File System Access API misses a good idea, why to choose File System Access API over non-experimental File API. It should be extended by modifying and saving the GeoJSON.

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo.
Feel free to update the example there, it's a single html file, I don't have hard feelings eitherway.
Sorry for the super late response...
