### ISSUE TITLE
Failed to run "npm start"

### ISSUE THREAD

**Issue by vudq** [maplibre/maplibre-gl-js-docs#81]
Dear all,
I'am trying to run "npm start" on Windows 10 but it's failed as below picture. 
![image](https://user-images.githubusercontent.com/5925915/129324958-cf89ee5c-db0b-4603-ae69-28c06e3a1614.png)
Any suggestion on fixing this?
Thanks,

**Comment by astridx** [comment]
Dear @vudq ,
Have you set up the environment as described here? : https://github.com/maplibre/maplibre-gl-js-docs#setting-up-the-development-environment

Did you see a error or a warning by this?

**Comment by vudq** [comment]
I have do it without error or a warning.

**Comment by astridx** [comment]
Which node version are you using? Maybe `nvm use && npm start` is worth a try?
( see https://github.com/maplibre/maplibre-gl-js-docs#running-the-documentation-server-locally)

**Comment by vudq** [comment]
> Which node version are you using? Maybe `nvm use && npm start` is worth a try?
> ( see https://github.com/maplibre/maplibre-gl-js-docs#running-the-documentation-server-locally)

I'am using node v12.13.1

**Comment by astridx** [comment]
Did you try `nvm use && npm start` ?

**Comment by vudq** [comment]
> Dear @vudq ,
> Have you set up the environment as described here? : https://github.com/maplibre/maplibre-gl-js-docs#setting-up-the-development-environment
> 
> Did you see a error or a warning by this?

This is result of "npm ci" in my machine
![image](https://user-images.githubusercontent.com/5925915/129327772-3ca56747-bc7e-46ac-8882-8abb2e61f9da.png)
![image](https://user-images.githubusercontent.com/5925915/129327845-bfb62664-4a24-4877-b768-6384329e5e71.png)

**Comment by vudq** [comment]
> Did you try `nvm use && npm start` ?
As recommandation in requirement "The NPM scripts will not run on Windows, but work perfectly with WSL2."
now i'm using  WSL and it works,
@astridx , Thanks you very much.
