### ISSUE TITLE
`Verion 9 of Highlight.js has reached EOL` - outdated version of highlight.js

### ISSUE THREAD

**Issue by JannikGM** [maplibre/maplibre-gl-js-docs#84]
This message is shown during `npm ci`:

>  Verion 9 of Highlight.js has reached EOL.  It will no longer
>  be supported or receive security updates in the future.
>  Please upgrade to version 10 or encourage your indirect
>  dependencies to do so.
>
>  For more info:
>
>  https://github.com/highlightjs/highlight.js/issues/2877
>  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md

I was using:

* node: v12.22.0
* npm: 6.14.11

**Comment by HarelM** [comment]
New docs are now part of the maplibre-gl-js repo. I believe this is no longer and issue, but if it is please open a new issue there.
